// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDrnxpG6_nsssAq2NO5H19tccLInsHiEG4",
      authDomain: "iclean-59a5b.firebaseapp.com",
      projectId: "iclean-59a5b",
      storageBucket: "iclean-59a5b.appspot.com",
      messagingSenderId: "475804456084",
      appId: "1:475804456084:web:07074e4182be1cb8b35081",
      measurementId: "G-BB4KX8W7VN");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDrnxpG6_nsssAq2NO5H19tccLInsHiEG4",
    projectId: "iclean-59a5b",
    storageBucket: "iclean-59a5b.appspot.com",
    messagingSenderId: "475804456084",
    appId: "1:475804456084:web:07074e4182be1cb8b35081",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDW_gmXEeLfaP9rMrfI4ps-TJcf_xyrVA',
    appId: '1:81955253683:ios:3dc0e6cb2bda28d4332fc6',
    messagingSenderId: '81955253683',
    projectId: 'iclean-project-76967',
    storageBucket: 'iclean-project-76967.appspot.com',
    iosClientId:
        '81955253683-t5s83amg9fcd6ep8cn8iq44plq3c8d3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.swdProjectClatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDW_gmXEeLfaP9rMrfI4ps-TJcf_xyrVA',
    appId: '1:81955253683:ios:3dc0e6cb2bda28d4332fc6',
    messagingSenderId: '81955253683',
    projectId: 'iclean-project-76967',
    storageBucket: 'iclean-project-76967.appspot.com',
    iosClientId:
        '81955253683-t5s83amg9fcd6ep8cn8iq44plq3c8d3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.swdProjectClatt',
  );
}
