// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDrnxpG6_nsssAq2NO5H19tccLInsHiEG4",
      authDomain: "iclean-59a5b.firebaseapp.com",
      projectId: "iclean-59a5b",
      storageBucket: "iclean-59a5b.appspot.com",
      databaseURL:
          "https://iclean-59a5b-default-rtdb.asia-southeast1.firebasedatabase.app",
      messagingSenderId: "475804456084",
      appId: "1:475804456084:web:07074e4182be1cb8b35081",
      measurementId: "G-BB4KX8W7VN");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDrnxpG6_nsssAq2NO5H19tccLInsHiEG4",
    projectId: "iclean-59a5b",
    storageBucket: "iclean-59a5b.appspot.com",
    databaseURL:
        "https://iclean-59a5b-default-rtdb.asia-southeast1.firebasedatabase.app",
    messagingSenderId: "475804456084",
    appId: "1:475804456084:web:07074e4182be1cb8b35081",
  );
}
